version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4566:4566' # Default port for LocalStack
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=dynamodb,lambda
      - DEBUG=1 # Enable debugging output
      - KINESIS_PROVIDER=kinesalite
      - LAMBDA_LIMITS_CODE_SIZE_ZIPPED=524288000
      - LAMBDA_LIMITS_CREATE_FUNCTION_REQUEST_SIZE=524288000
    volumes:
      - './:/etc/localstack/init/ready.d/' # Mount your project directory to automatically run scripts
      - '/var/run/docker.sock:/var/run/docker.sock' # Mount the Docker socket to allow LocalStack to manage Docker containers
      - './target/usermanager-0.0.1-SNAPSHOT.jar:/tmp/usermanager-0.0.1-SNAPSHOT.jar' # Mount the jar file to be used by the lambda
    networks:
      - backend

  usermanager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - amazon.dynamodb.endpoint=http://localstack:4566/
      - amazon.aws.accesskey=key
      - amazon.aws.secretkey=key2
    networks:
      - backend

networks:
  backend:
